language: elixir

dist: trusty
sudo: false

matrix:
  include:
  - elixir: 1.9.1
    otp_release: 22.0.7
  - elixir: 1.8.2
    otp_release: 21.3.8
  - elixir: 1.7.2
    otp_release: 21.0
  - elixir: 1.7.2
    otp_release: 20.3.1
  - elixir: 1.6.6
    otp_release: 19.3
  - elixir: 1.5.3
    otp_release: 18.3
  - elixir: 1.5.3
    otp_release: 17.5
  - elixir: 1.4.5
    otp_release: 17.5
